image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install
    command: dfx start --background && dfx deploy

ports:
  - port: 8000
    onOpen: open-preview

vscode:
  extensions:
    - ms-vscode.vscode-typescript-next
